### ISSUE TITLE
registration.properties is missing

### ISSUE THREAD

**Issue by holviberker** [op-developer/psd2-registration-example#3]
Installation guideline says:

> Fill in the required values in registration.properties (in the root directory of this project).

However, there is file named `registration.properties` in the repository:

```sh
$ git ls-files | grep registration.properties
```

As a result of this, the following command fails:

```sh
$ java -jar target/oop-registration-example-fat.jar
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: registration.properties (No such file or directory)
	at fi.op.psd2.registration.EnvironmentConfig.<init>(EnvironmentConfig.java:28)
	at fi.op.psd2.registration.SandboxRegistrator.<init>(SandboxRegistrator.java:28)
	at fi.op.psd2.registration.SandboxRegistrationExample.main(SandboxRegistrationExample.java:5)
Caused by: java.io.FileNotFoundException: registration.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:110)
	at fi.op.psd2.registration.EnvironmentConfig.<init>(EnvironmentConfig.java:26)
	... 2 more
```

I think a stub `registration.properties` was initially forgotted to be committed because of this line:

https://github.com/op-developer/psd2-registration-example/blob/1f0b04f1655a20019ca9986f850f9924b1c3e08e/.gitignore#L14

**Comment by markusl** [comment]
The `registration.properties` values are described in the README of the repository. Please let me know if this helps.

Br,
Markus

**Comment by holviberker** [comment]
True, I ended up creating the file with the values described in README. However, in my opinion, the README implies that the file is already generated in the source tree:

> Fill in the required values in registration.properties (in the root directory of this project).

It might be better to clarify the wording or add a stub `registration.properties.tpl` file to make the installation faster.

Thank you.
